on: [push]

jobs:
  test-dev:
    runs-on: ubuntu-latest
    name: Testing dev
    steps:
      - name: Providers status
        id: hello
        uses: gardarik/provider-status-action@develop
        with:
          providers: 'aws.1'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"